# Generated by Django 6.0.6 on 2026-06-11 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_scores', models.JSONField(default=dict, help_text='{"dimension_code": {"score": 85, "max": 100, "level": "良好"}}', verbose_name='维度得分')),
                ('total_score', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='总分')),
                ('max_score', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='满分')),
                ('score_percent', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='得分率(%)')),
                ('risk_tags', models.JSONField(default=list, help_text='["高焦虑","低抗压"]', verbose_name='风险标签')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='low', max_length=20, verbose_name='风险等级')),
                ('fit_score', models.DecimalField(decimal_places=1, default=0, help_text='0-100', max_digits=4, verbose_name='岗位适配度')),
                ('suggestion', models.TextField(blank=True, verbose_name='综合建议')),
                ('hr_comment', models.TextField(blank=True, verbose_name='HR人工评估意见')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='是否异常作答')),
                ('abnormal_reason', models.CharField(blank=True, max_length=200, verbose_name='异常原因')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '测评结果',
                'verbose_name_plural': '测评结果',
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='用时(秒)')),
                ('is_timeout', models.BooleanField(default=False, verbose_name='是否超时提交')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('invalid_reason', models.CharField(blank=True, max_length=100, verbose_name='无效原因')),
                ('device_info', models.CharField(blank=True, max_length=200, verbose_name='设备信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
            ],
            options={
                'verbose_name': '作答会话',
                'verbose_name_plural': '作答会话',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('channel', models.CharField(choices=[('sms', '短信'), ('email', '邮件')], max_length=20, verbose_name='渠道')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('content', models.TextField(help_text='支持 {{employee_name}} {{task_name}} {{access_code}} {{valid_until}} 等变量', verbose_name='内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '通知模板',
                'verbose_name_plural': '通知模板',
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='维度名称')),
                ('code', models.CharField(help_text='如 mental_health, stress_resistance', max_length=50, unique=True, verbose_name='编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '题目分类',
                'verbose_name_plural': '题目分类',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML报告')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='PDF文件')),
                ('is_pdf_generated', models.BooleanField(default=False, verbose_name='PDF已生成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='assessment.assessmentresult', verbose_name='测评结果')),
            ],
            options={
                'verbose_name': '测评报告',
                'verbose_name_plural': '测评报告',
            },
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessment.assessmentsession', verbose_name='作答会话'),
        ),
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('target_position', models.CharField(blank=True, help_text='如 通用/销售/技术/管理', max_length=100, verbose_name='适用岗位')),
                ('estimated_minutes', models.IntegerField(default=15, verbose_name='预计用时(分钟)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '测评模板',
                'verbose_name_plural': '测评模板',
            },
        ),
        migrations.CreateModel(
            name='AssessmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('draft', '未开始'), ('in_progress', '进行中'), ('paused', '已暂停'), ('finished', '已结束'), ('cancelled', '已作废')], default='draft', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='任务说明')),
                ('valid_from', models.DateTimeField(verbose_name='有效期开始')),
                ('valid_until', models.DateTimeField(verbose_name='有效期结束')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='作答时长(分钟)')),
                ('allow_retake', models.BooleanField(default=False, verbose_name='允许重新作答')),
                ('is_anonymous', models.BooleanField(default=False, help_text='入职测评默认识名', verbose_name='匿名作答')),
                ('max_retake_count', models.IntegerField(default=1, verbose_name='最大重答次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('branch', models.ForeignKey(blank=True, help_text='超管可指定分公司，HR管理员自动关联', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch', verbose_name='所属分公司')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmenttemplate', verbose_name='测评模板')),
            ],
            options={
                'verbose_name': '测评任务',
                'verbose_name_plural': '测评任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='应聘岗位')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='所属部门')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='入职时间')),
                ('status', models.CharField(choices=[('pending', '待测评'), ('assessed', '已测评'), ('excluded', '已排除')], default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch', verbose_name='所属分公司')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('likert5', '量表题(5级)'), ('likert7', '量表题(7级)')], default='likert5', max_length=20, verbose_name='题型')),
                ('text', models.TextField(verbose_name='题目内容')),
                ('description', models.TextField(blank=True, verbose_name='说明/指导语')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('score', models.DecimalField(decimal_places=1, default=1.0, max_digits=5, verbose_name='默认分值')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='该题在维度中的权重系数', max_digits=4, verbose_name='权重')),
                ('is_reversed', models.BooleanField(default=False, help_text='量表题中高分表示消极则为反向', verbose_name='反向计分')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('review_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='approved', max_length=20, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.questioncategory', verbose_name='所属维度')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='如 A、B、C 或 1、2、3', max_length=10, verbose_name='选项标签')),
                ('text', models.CharField(max_length=200, verbose_name='选项内容')),
                ('score', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='分值')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessment.question', verbose_name='所属题目')),
            ],
            options={
                'verbose_name': '题目选项',
                'verbose_name_plural': '题目选项',
                'ordering': ['question', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='测评码')),
                ('status', models.CharField(choices=[('pending', '待作答'), ('in_progress', '作答中'), ('completed', '已完成'), ('expired', '已超时'), ('invalid', '已作废')], default='pending', max_length=20, verbose_name='状态')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('reminded_at', models.DateTimeField(blank=True, null=True, verbose_name='最后提醒时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assessment.employee', verbose_name='员工')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assessment.assessmenttask', verbose_name='测评任务')),
            ],
            options={
                'verbose_name': '任务分配',
                'verbose_name_plural': '任务分配',
                'unique_together': {('task', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='assessment.taskassignment', verbose_name='任务分配'),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessment.taskassignment', verbose_name='任务分配'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='选择题存选项ID列表JSON，量表题存数值', verbose_name='原始答案')),
                ('score', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='得分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作答时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.assessmentsession', verbose_name='作答会话')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '答案记录',
                'verbose_name_plural': '答案记录',
                'unique_together': {('session', 'question')},
            },
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='权重')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_questions', to='assessment.question')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_questions', to='assessment.assessmenttemplate')),
            ],
            options={
                'verbose_name': '模板题目',
                'verbose_name_plural': '模板题目',
                'ordering': ['template', 'sort_order'],
                'unique_together': {('template', 'question')},
            },
        ),
    ]
